### ISSUE TITLE
Spotify User and Password

### ISSUE THREAD

**Issue by clerissonferreira** [balena-io-projects/balena-sound#73] opened 2019-12-18 17:43 UTC
The project uses raspotify, in the raspotify settings there is the option to enter the username and password, if you are a subscriber, to make the device visible on Spotify Connect over the Internet. In this project how do I set this up?

**Comment by AlexProgrammerDE** [comment] 2019-12-19 16:49
Hello @clerissonferreira . This feature is at the moment not implemented. It is a nice idea. So i will try to implement this. You will need only in the future to set two enviroment variables in the cloud dashboard (You Username/E-Mail and your password). :smiley_cat:

**Comment by clerissonferreira** [comment] 2019-12-19 17:31
Thanks for listening. Glad you can help me.

**Comment by AlexProgrammerDE** [comment] 2019-12-19 20:57
Same with this again: https://github.com/AlexProgrammerDE/balena-sound/tree/spotify-login

Please dont wonder if the wifi-connect container disappears. It is not in this branch. You can use both of them, when my PR gets approved. 👍 

PS: I cant test if this works. I dont know how to do this, so you can try this.

**Comment by AlexProgrammerDE** [comment] 2020-01-02 13:18
@clerissonferreira could you please close this issue? I implemented this feature in a PR. You can read more about it in the README.

**Comment by chrisys** [comment] 2020-01-07 11:43
This feature works perfectly - closing for now. @clerissonferreira please reopen if you're still having trouble with it.

**Closed by chrisys** 2020-01-07 11:43 UTC

**Comment by peteretep** [comment] 2020-01-28 10:00
I'm having trouble with this - using my spotify username and password will not authenticate. 
My password has spaces in it - could that be the cause of the issue? I'll look into it tonight

**Comment by peteretep** [comment] 2020-01-29 22:30
Confirmed that a password with spaces in it does not work. I didn't bother fixing, just changed my password instead.

**Comment by tmigone** [comment] 2020-01-30 12:35
Hey thanks for letting us know @peteretep. I'm opening a separate issue to track this and get it fixed soon.
