### ISSUE TITLE
Support for Google Cast?

### ISSUE THREAD

**Issue by the4anoni** [balena-io-projects/balena-sound#504] opened 2021-10-26 08:22 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement Google Cast support.

**Describe alternatives you've considered**
Android device withCastReceiver app (sadly it can't receive audio only).

**Additional context**
Google Cast would be useful as AirPlay on Apple Devices. For now Android Users have Spotify Connect (which require Spotify) or Bluetooth (which isn't lossless).

**Comment by eborchardt** [comment] 2022-01-19 04:02
I would also love to see this added. I am a longtime user of YouTube Music and have my home fitted with Google speakers in nearly every room. I would love to have something more a little more robust, like a stereo receiver, connected to a Raspberry Pi running balenaSound.

**Comment by nicolas-sora** [comment] 2022-02-06 03:29
Some development started here but no progress so far unfortunately. Would love this as well

https://github.com/balenalabs/balena-sound/issues/102
Duplicate of #102

**Comment by tmigone** [comment] 2022-04-05 14:00
Let's use #102 for google cast enhancement request

**Closed as completed by tmigone** 2022-04-05 14:00 UTC
Labels: enhancement
